import React, { useState, createContext, useContext, useEffect, useCallback } from 'react';

// --- LANGUAGE CONTEXT & TRANSLATIONS ---

const translations = {
  en: {
    nav_home: "Home", nav_jobs: "Find Jobs", nav_create: "Create Profile", nav_requests: "Requests",
    home_welcome_title: "Welcome to X'PAT Jobs",
    home_welcome_subtitle: "Your platform for finding work and workers in Malaysia.",
    home_card_find_title: "Find a Job Seeker",
    home_card_find_desc: "Browse and search profiles of available workers.",
    home_card_create_title: "Create Your Profile",
    home_card_create_desc: "Get discovered by employers by creating your job profile.",
    home_card_requests_title: "Manage Requests",
    home_card_requests_desc: "Check the status of your contact requests.",
    jobboard_title: "Available Job Seekers",
    jobboard_subtitle: "Connect with talented workers looking for opportunities",
    jobboard_stat_profiles: "Active Profiles",
    jobboard_stat_new: "New Today",
    jobboard_search_placeholder: "Search by skills, location, nationality...",
    jobboard_loading: "Loading profiles...",
    jobboard_no_profiles_title: "No Profiles Found",
    jobboard_no_profiles_desc: "Try adjusting your search or filter.",
    jobboard_card_skills: "Skills",
    jobboard_card_views: "views",
    jobboard_card_expires_in: "Expires in",
    jobboard_card_day: "day",
    jobboard_card_days: "days",
    jobboard_detail_experience: "Experience",
    jobboard_detail_location: "Location",
    jobboard_detail_nationality: "Nationality",
    jobboard_detail_visa: "Visa Status",
    jobboard_detail_views: "Views",
    jobboard_detail_days_left: "Days Left",
    jobboard_detail_request_btn: "Request Contact",
    jobboard_request_modal_title: "Request Contact",
    jobboard_request_modal_desc: "Your details will be sent to {name}.",
    jobboard_request_modal_name_placeholder: "Your Name or Company",
    jobboard_request_modal_phone_placeholder: "Your WhatsApp Number",
    jobboard_request_modal_cancel: "Cancel",
    jobboard_request_modal_send: "Send Request",
    jobboard_request_modal_sending: "Sending...",
    jobboard_toast_success: "Your contact request has been sent!",
    jobboard_filters_all: "All Jobs",
    jobboard_filters_factory: "Factory Worker",
    jobboard_filters_restaurant: "Restaurant/Kitchen Helper",
    jobboard_filters_cleaner: "Cleaner/Housekeeper",
    jobboard_filters_construction: "Construction Worker",
    jobboard_filters_security: "Security Guard",
    jobboard_filters_driver: "Driver",
    jobboard_filters_technician: "Technician/Mechanic",
    jobboard_filters_packing: "Packing/Warehouse",
    jobboard_filters_general: "General Worker",
    create_profile_title: "Create Your Job Profile",
    create_profile_subtitle: "AI will help you stand out to employers.",
    create_profile_progress: "Progress",
    create_profile_q_name: "Hello! Let's create your job profile. What's your name?",
    create_profile_q_age: "Great! What's your age range?",
    create_profile_q_visa: "What type of visa or work permit do you have?",
    create_profile_q_nationality: "What is your nationality?",
    create_profile_q_experience: "How many years of work experience do you have?",
    create_profile_q_job: "What type of job are you looking for?",
    create_profile_q_skills: "Describe your skills and experience (e.g., machine operation, welding, cooking, can work night shifts).",
    create_profile_q_phone: "What's your active WhatsApp number?",
    create_profile_q_location: "Finally, which area in Malaysia do you prefer to work in?",
    create_profile_phone_placeholder: "+60123456789",
    create_profile_location_placeholder: "e.g., Kuala Lumpur, Johor Bahru",
    create_profile_validation_skills: "Please provide more details (min 10 characters).",
    create_profile_validation_phone: "Please enter a valid Malaysian phone number.",
    create_profile_validation_required: "This field is required.",
    create_profile_submit: "Submit",
    create_profile_skip: "Skip",
    create_profile_loading: "AI is creating your professional profile...",
    create_profile_success_title: "Profile Created!",
    create_profile_success_desc: "Your job profile is now live for employers to see.",
    create_profile_success_btn_board: "View Job Board",
    create_profile_success_btn_another: "Create Another",
    create_profile_anonymous: "Anonymous",
    requests_portal_title: "My Requests",
    requests_portal_subtitle: "Please select your role to continue.",
    requests_portal_seeker_title: "I am a Job Seeker",
    requests_portal_seeker_desc: "View and manage contact requests from employers for your profile.",
    requests_portal_employer_title: "I am an Employer",
    requests_portal_employer_desc: "Track the status of the contact requests you have sent to job seekers.",
    seeker_requests_login_title: "My Contact Requests",
    seeker_requests_login_desc: "Enter the phone number you used for your job post to see requests from employers.",
    seeker_requests_login_placeholder: "Your WhatsApp Number",
    seeker_requests_login_btn: "View My Requests",
    seeker_requests_title: "Manage Requests",
    seeker_requests_subtitle: "Approve or reject requests from employers.",
    seeker_requests_stat_total: "Total",
    seeker_requests_stat_pending: "Pending",
    seeker_requests_stat_approved: "Approved",
    seeker_requests_no_requests_title: "No Requests Yet",
    seeker_requests_no_requests_desc: "When an employer requests your contact, it will appear here.",
    seeker_requests_card_approve_confirm: "Approve this request? Your contact number will be shared.",
    seeker_requests_card_reject_confirm: "Reject this request? The employer will not get your number.",
    seeker_requests_card_status_pending: "Pending",
    seeker_requests_card_status_approved: "Approved",
    seeker_requests_card_status_rejected: "Rejected",
    seeker_requests_card_pending_desc: "Only approve if you want to share your number. They will be able to contact you on WhatsApp.",
    seeker_requests_card_approved_desc: "Contact shared! Employer can now reach you.",
    seeker_requests_card_rejected_desc: "Request rejected. Your contact was not shared.",
    seeker_requests_card_approve_btn: "Approve",
    seeker_requests_card_reject_btn: "Reject",
    employer_requests_login_title: "Employer Requests",
    employer_requests_login_desc: "Enter your phone number to track the status of your contact requests.",
    employer_requests_login_btn: "Track My Requests",
    employer_requests_title: "Request Status",
    employer_requests_subtitle: "Track your requests sent to job seekers.",
    employer_requests_stat_total: "Total",
    employer_requests_stat_approved: "Approved",
    employer_requests_stat_pending: "Pending",
    employer_requests_no_requests_title: "No Requests Sent",
    employer_requests_no_requests_desc: "You haven't sent any contact requests from this phone number.",
    employer_requests_card_requested_on: "Requested on",
    employer_requests_card_status_pending: "Pending",
    employer_requests_card_status_approved: "Approved",
    employer_requests_card_status_rejected: "Rejected",
    employer_requests_card_approved_title: "Contact Approved!",
    employer_requests_card_whatsapp_btn: "Chat on WhatsApp",
    employer_requests_card_pending_desc: "Waiting for the job seeker to review your request.",
    employer_requests_card_rejected_desc: "Your request was declined by the job seeker.",
    splash_welcome: "Welcome to",
  },
  bn: {
    nav_home: "হোম", nav_jobs: "চাকরি খুঁজুন", nav_create: "প্রোফাইল তৈরি", nav_requests: "অনুরোধ",
    home_welcome_title: "X'PAT Jobs-এ স্বাগতম",
    home_welcome_subtitle: "মালয়েশিয়ায় কাজ এবং কর্মী খোঁজার জন্য আপনার প্ল্যাটফর্ম।",
    home_card_find_title: "চাকরি প্রার্থী খুঁজুন",
    home_card_find_desc: "উপলব্ধ কর্মীদের প্রোফাইল ব্রাউজ এবং অনুসন্ধান করুন।",
    home_card_create_title: "আপনার প্রোফাইল তৈরি করুন",
    home_card_create_desc: "আপনার চাকরির প্রোফাইল তৈরি করে নিয়োগকারীদের দ্বারা আবিষ্কৃত হন।",
    home_card_requests_title: "অনুরোধ পরিচালনা করুন",
    home_card_requests_desc: "আপনার যোগাযোগের অনুরোধগুলির স্থিতি পরীক্ষা করুন।",
    jobboard_title: "উপলব্ধ চাকরি প্রার্থী",
    jobboard_subtitle: "সুযোগের সন্ধানে প্রতিভাবান কর্মীদের সাথে সংযোগ স্থাপন করুন",
    jobboard_stat_profiles: "সক্রিয় প্রোফাইল",
    jobboard_stat_new: "আজ নতুন",
    jobboard_search_placeholder: "দক্ষতা, অবস্থান, জাতীয়তা দ্বারা অনুসন্ধান করুন...",
    jobboard_loading: "প্রোফাইল লোড হচ্ছে...",
    jobboard_no_profiles_title: "কোন প্রোফাইল পাওয়া যায়নি",
    jobboard_no_profiles_desc: "আপনার অনুসন্ধান বা ফিল্টার সামঞ্জস্য করার চেষ্টা করুন।",
    jobboard_card_skills: "দক্ষতা",
    jobboard_card_views: "বার দেখা হয়েছে",
    jobboard_card_expires_in: "মেয়াদ শেষ হবে",
    jobboard_card_day: "দিন",
    jobboard_card_days: "দিন",
    jobboard_detail_experience: "অভিজ্ঞতা",
    jobboard_detail_location: "অবস্থান",
    jobboard_detail_nationality: "জাতীয়তা",
    jobboard_detail_visa: "ভিসার স্থিতি",
    jobboard_detail_views: "দেখা হয়েছে",
    jobboard_detail_days_left: "দিন বাকি",
    jobboard_detail_request_btn: "যোগাযোগের জন্য অনুরোধ",
    jobboard_request_modal_title: "যোগাযোগের জন্য অনুরোধ",
    jobboard_request_modal_desc: "আপনার বিবরণ {name} এর কাছে পাঠানো হবে।",
    jobboard_request_modal_name_placeholder: "আপনার নাম বা সংস্থা",
    jobboard_request_modal_phone_placeholder: "আপনার হোয়াটসঅ্যাপ নম্বর",
    jobboard_request_modal_cancel: "বাতিল",
    jobboard_request_modal_send: "অনুরোধ পাঠান",
    jobboard_request_modal_sending: "পাঠানো হচ্ছে...",
    jobboard_toast_success: "আপনার যোগাযোগের অনুরোধ পাঠানো হয়েছে!",
    jobboard_filters_all: "সব চাকরি",
    jobboard_filters_factory: "কারখানার কর্মী",
    jobboard_filters_restaurant: "রেস্তোরাঁ/রান্নাঘরের সাহায্যকারী",
    jobboard_filters_cleaner: "ক্লিনার/হাউসকিপার",
    jobboard_filters_construction: "নির্মাণ কর্মী",
    jobboard_filters_security: "নিরাপত্তা প্রহরী",
    jobboard_filters_driver: "ড্রাইভার",
    jobboard_filters_technician: "টেকনিশিয়ান/মেকানিক",
    jobboard_filters_packing: "প্যাকিং/গুদাম",
    jobboard_filters_general: "সাধারণ কর্মী",
    create_profile_title: "আপনার চাকরির প্রোফাইল তৈরি করুন",
    create_profile_subtitle: "AI আপনাকে নিয়োগকারীদের কাছে আলাদা হতে সাহায্য করবে।",
    create_profile_progress: "অগ্রগতি",
    create_profile_q_name: "হ্যালো! আসুন আপনার চাকরির প্রোফাইল তৈরি করি। আপনার নাম কি?",
    create_profile_q_age: "দারুণ! আপনার বয়স কত?",
    create_profile_q_visa: "আপনার কি ধরনের ভিসা বা ওয়ার্ক পারমিট আছে?",
    create_profile_q_nationality: "আপনার জাতীয়তা কি?",
    create_profile_q_experience: "আপনার কত বছরের কাজের অভিজ্ঞতা আছে?",
    create_profile_q_job: "আপনি কি ধরনের চাকরি খুঁজছেন?",
    create_profile_q_skills: "আপনার দক্ষতা এবং অভিজ্ঞতা বর্ণনা করুন (যেমন, মেশিন চালানো, ওয়েল্ডিং, রান্না, রাতের শিফটে কাজ করতে পারা)।",
    create_profile_q_phone: "আপনার সক্রিয় হোয়াটসঅ্যাপ নম্বর কি?",
    create_profile_q_location: "অবশেষে, মালয়েশিয়ার কোন এলাকায় আপনি কাজ করতে পছন্দ করেন?",
    create_profile_phone_placeholder: "+৬০১২৩৪৫৬৭৮৯",
    create_profile_location_placeholder: "যেমন, কুয়ালালামপুর, জোহর বাহরু",
    create_profile_validation_skills: "অনুগ্রহ করে আরও বিশদ বিবরণ দিন (ন্যূনতম ১০ অক্ষর)।",
    create_profile_validation_phone: "অনুগ্রহ করে একটি বৈধ মালয়েশিয়ান ফোন নম্বর লিখুন।",
    create_profile_validation_required: "এই ক্ষেত্রটি প্রয়োজনীয়।",
    create_profile_submit: "জমা দিন",
    create_profile_skip: "এড়িয়ে যান",
    create_profile_loading: "AI আপনার পেশাদার প্রোফাইল তৈরি করছে...",
    create_profile_success_title: "প্রোফাইল তৈরি হয়েছে!",
    create_profile_success_desc: "আপনার চাকরির প্রোফাইল এখন নিয়োগকর্তারা দেখতে পাবে।",
    create_profile_success_btn_board: "জব বোর্ড দেখুন",
    create_profile_success_btn_another: "আরেকটি তৈরি করুন",
    create_profile_anonymous: "নামহীন",
    requests_portal_title: "আমার অনুরোধ",
    requests_portal_subtitle: "চালিয়ে যেতে অনুগ্রহ করে আপনার ভূমিকা নির্বাচন করুন।",
    requests_portal_seeker_title: "আমি একজন চাকরি প্রার্থী",
    requests_portal_seeker_desc: "আপনার প্রোফাইলের জন্য নিয়োগকারীদের কাছ থেকে যোগাযোগের অনুরোধ দেখুন এবং পরিচালনা করুন।",
    requests_portal_employer_title: "আমি একজন নিয়োগকর্তা",
    requests_portal_employer_desc: "আপনি চাকরি প্রার্থীদের কাছে যে যোগাযোগের অনুরোধ পাঠিয়েছেন তার স্থিতি ট্র্যাক করুন।",
    seeker_requests_login_title: "আমার যোগাযোগের অনুরোধ",
    seeker_requests_login_desc: "নিয়োগকারীদের কাছ থেকে অনুরোধ দেখতে আপনার চাকরির পোস্টের জন্য ব্যবহৃত ফোন নম্বরটি লিখুন।",
    seeker_requests_login_placeholder: "আপনার হোয়াটসঅ্যাপ নম্বর",
    seeker_requests_login_btn: "আমার অনুরোধ দেখুন",
    seeker_requests_title: "অনুরোধ পরিচালনা করুন",
    seeker_requests_subtitle: "নিয়োগকারীদের কাছ থেকে অনুরোধ অনুমোদন বা প্রত্যাখ্যান করুন।",
    seeker_requests_stat_total: "মোট",
    seeker_requests_stat_pending: "বিচারাধীন",
    seeker_requests_stat_approved: "অনুমোদিত",
    seeker_requests_no_requests_title: "এখনও কোন অনুরোধ নেই",
    seeker_requests_no_requests_desc: "যখন একজন নিয়োগকর্তা আপনার যোগাযোগের জন্য অনুরোধ করবে, তখন এটি এখানে প্রদর্শিত হবে।",
    seeker_requests_card_approve_confirm: "এই অনুরোধটি অনুমোদন করবেন? আপনার যোগাযোগ নম্বর শেয়ার করা হবে।",
    seeker_requests_card_reject_confirm: "এই অনুরোধটি প্রত্যাখ্যান করবেন? নিয়োগকর্তা আপনার নম্বর পাবেন না।",
    seeker_requests_card_status_pending: "বিচারাধীন",
    seeker_requests_card_status_approved: "অনুমোদিত",
    seeker_requests_card_status_rejected: "প্রত্যাখ্যাত",
    seeker_requests_card_pending_desc: "শুধুমাত্র যদি আপনি আপনার নম্বর শেয়ার করতে চান তবেই অনুমোদন করুন। তারা আপনাকে হোয়াটসঅ্যাপে যোগাযোগ করতে পারবে।",
    seeker_requests_card_approved_desc: "যোগাযোগ শেয়ার করা হয়েছে! নিয়োগকর্তা এখন আপনার সাথে যোগাযোগ করতে পারবেন।",
    seeker_requests_card_rejected_desc: "অনুরোধ প্রত্যাখ্যান করা হয়েছে। আপনার যোগাযোগ শেয়ার করা হয়নি।",
    seeker_requests_card_approve_btn: "অনুমোদন",
    seeker_requests_card_reject_btn: "প্রত্যাখ্যান",
    employer_requests_login_title: "নিয়োগকর্তার অনুরোধ",
    employer_requests_login_desc: "আপনার যোগাযোগের অনুরোধগুলির স্থিতি ট্র্যাক করতে আপনার ফোন নম্বর লিখুন।",
    employer_requests_login_btn: "আমার অনুরোধ ট্র্যাক করুন",
    employer_requests_title: "অনুরোধের স্থিতি",
    employer_requests_subtitle: "চাকরি প্রার্থীদের কাছে পাঠানো আপনার অনুরোধগুলি ট্র্যাক করুন।",
    employer_requests_stat_total: "মোট",
    employer_requests_stat_approved: "অনুমোদিত",
    employer_requests_stat_pending: "বিচারাধীন",
    employer_requests_no_requests_title: "কোন অনুরোধ পাঠানো হয়নি",
    employer_requests_no_requests_desc: "আপনি এই ফোন নম্বর থেকে কোন যোগাযোগের অনুরোধ পাঠাননি।",
    employer_requests_card_requested_on: "অনুরোধ করা হয়েছে",
    employer_requests_card_status_pending: "বিচারাধীন",
    employer_requests_card_status_approved: "অনুমোদিত",
    employer_requests_card_status_rejected: "প্রত্যাখ্যাত",
    employer_requests_card_approved_title: "যোগাযোগ অনুমোদিত!",
    employer_requests_card_whatsapp_btn: "হোয়াটসঅ্যাপে চ্যাট করুন",
    employer_requests_card_pending_desc: "চাকরি প্রার্থীর আপনার অনুরোধ পর্যালোচনা করার জন্য অপেক্ষা করা হচ্ছে।",
    employer_requests_card_rejected_desc: "আপনার অনুরোধটি চাকরি প্রার্থী দ্বারা প্রত্যাখ্যান করা হয়েছে।",
    splash_welcome: "স্বাগতম",
  },
  ms: {
    nav_home: "Utama", nav_jobs: "Cari Kerja", nav_create: "Cipta Profil", nav_requests: "Permintaan",
    home_welcome_title: "Selamat Datang ke X'PAT Jobs",
    home_welcome_subtitle: "Platform anda untuk mencari kerja dan pekerja di Malaysia.",
    home_card_find_title: "Cari Pencari Kerja",
    home_card_find_desc: "Layari dan cari profil pekerja yang tersedia.",
    home_card_create_title: "Cipta Profil Anda",
    home_card_create_desc: "Dapatkan perhatian majikan dengan mencipta profil kerja anda.",
    home_card_requests_title: "Urus Permintaan",
    home_card_requests_desc: "Semak status permintaan hubungan anda.",
    jobboard_title: "Pencari Kerja Tersedia",
    jobboard_subtitle: "Berhubung dengan pekerja berbakat yang mencari peluang",
    jobboard_stat_profiles: "Profil Aktif",
    jobboard_stat_new: "Baru Hari Ini",
    jobboard_search_placeholder: "Cari mengikut kemahiran, lokasi, warganegara...",
    jobboard_loading: "Memuatkan profil...",
    jobboard_no_profiles_title: "Tiada Profil Ditemui",
    jobboard_no_profiles_desc: "Cuba laraskan carian atau penapis anda.",
    jobboard_card_skills: "Kemahiran",
    jobboard_card_views: "kali dilihat",
    jobboard_card_expires_in: "Tamat dalam",
    jobboard_card_day: "hari",
    jobboard_card_days: "hari",
    jobboard_detail_experience: "Pengalaman",
    jobboard_detail_location: "Lokasi",
    jobboard_detail_nationality: "Warganegara",
    jobboard_detail_visa: "Status Visa",
    jobboard_detail_views: "Dilihat",
    jobboard_detail_days_left: "Hari Berbaki",
    jobboard_detail_request_btn: "Minta Maklumat Hubungan",
    jobboard_request_modal_title: "Minta Maklumat Hubungan",
    jobboard_request_modal_desc: "Butiran anda akan dihantar kepada {name}.",
    jobboard_request_modal_name_placeholder: "Nama Anda atau Syarikat",
    jobboard_request_modal_phone_placeholder: "Nombor WhatsApp Anda",
    jobboard_request_modal_cancel: "Batal",
    jobboard_request_modal_send: "Hantar Permintaan",
    jobboard_request_modal_sending: "Menghantar...",
    jobboard_toast_success: "Permintaan hubungan anda telah dihantar!",
    jobboard_filters_all: "Semua Kerja",
    jobboard_filters_factory: "Pekerja Kilang",
    jobboard_filters_restaurant: "Pembantu Restoran/Dapur",
    jobboard_filters_cleaner: "Pembersih/Pengemas Rumah",
    jobboard_filters_construction: "Pekerja Binaan",
    jobboard_filters_security: "Pengawal Keselamatan",
    jobboard_filters_driver: "Pemandu",
    jobboard_filters_technician: "Juruteknik/Mekanik",
    jobboard_filters_packing: "Pembungkusan/Gudang",
    jobboard_filters_general: "Pekerja Am",
    create_profile_title: "Cipta Profil Kerja Anda",
    create_profile_subtitle: "AI akan membantu anda menonjol kepada majikan.",
    create_profile_progress: "Kemajuan",
    create_profile_q_name: "Helo! Mari cipta profil kerja anda. Siapakah nama anda?",
    create_profile_q_age: "Hebat! Apakah lingkungan umur anda?",
    create_profile_q_visa: "Apakah jenis visa atau permit kerja yang anda miliki?",
    create_profile_q_nationality: "Apakah warganegara anda?",
    create_profile_q_experience: "Berapa tahun pengalaman kerja yang anda miliki?",
    create_profile_q_job: "Apakah jenis pekerjaan yang anda cari?",
    create_profile_q_skills: "Terangkan kemahiran dan pengalaman anda (cth., pengendalian mesin, kimpalan, memasak, boleh kerja syif malam).",
    create_profile_q_phone: "Apakah nombor WhatsApp anda yang aktif?",
    create_profile_q_location: "Akhir sekali, di kawasan mana di Malaysia yang anda lebih suka bekerja?",
    create_profile_phone_placeholder: "+60123456789",
    create_profile_location_placeholder: "cth., Kuala Lumpur, Johor Bahru",
    create_profile_validation_skills: "Sila berikan butiran lanjut (min 10 aksara).",
    create_profile_validation_phone: "Sila masukkan nombor telefon Malaysia yang sah.",
    create_profile_validation_required: "Ruangan ini diperlukan.",
    create_profile_submit: "Hantar",
    create_profile_skip: "Langkau",
    create_profile_loading: "AI sedang mencipta profil profesional anda...",
    create_profile_success_title: "Profil Dicipta!",
    create_profile_success_desc: "Profil kerja anda kini disiarkan untuk dilihat oleh majikan.",
    create_profile_success_btn_board: "Lihat Papan Kerja",
    create_profile_success_btn_another: "Cipta Lagi",
    create_profile_anonymous: "Tanpa Nama",
    requests_portal_title: "Permintaan Saya",
    requests_portal_subtitle: "Sila pilih peranan anda untuk meneruskan.",
    requests_portal_seeker_title: "Saya Pencari Kerja",
    requests_portal_seeker_desc: "Lihat dan urus permintaan hubungan daripada majikan untuk profil anda.",
    requests_portal_employer_title: "Saya Majikan",
    requests_portal_employer_desc: "Jejaki status permintaan hubungan yang telah anda hantar kepada pencari kerja.",
    seeker_requests_login_title: "Permintaan Hubungan Saya",
    seeker_requests_login_desc: "Masukkan nombor telefon yang anda gunakan untuk siaran kerja anda untuk melihat permintaan daripada majikan.",
    seeker_requests_login_placeholder: "Nombor WhatsApp Anda",
    seeker_requests_login_btn: "Lihat Permintaan Saya",
    seeker_requests_title: "Urus Permintaan",
    seeker_requests_subtitle: "Luluskan atau tolak permintaan daripada majikan.",
    seeker_requests_stat_total: "Jumlah",
    seeker_requests_stat_pending: "Menunggu",
    seeker_requests_stat_approved: "Diluluskan",
    seeker_requests_no_requests_title: "Belum Ada Permintaan",
    seeker_requests_no_requests_desc: "Apabila majikan meminta maklumat hubungan anda, ia akan muncul di sini.",
    seeker_requests_card_approve_confirm: "Luluskan permintaan ini? Nombor telefon anda akan dikongsi.",
    seeker_requests_card_reject_confirm: "Tolak permintaan ini? Majikan tidak akan mendapat nombor anda.",
    seeker_requests_card_status_pending: "Menunggu",
    seeker_requests_card_status_approved: "Diluluskan",
    seeker_requests_card_status_rejected: "Ditolak",
    seeker_requests_card_pending_desc: "Hanya luluskan jika anda mahu berkongsi nombor anda. Mereka akan dapat menghubungi anda di WhatsApp.",
    seeker_requests_card_approved_desc: "Maklumat hubungan dikongsi! Majikan kini boleh menghubungi anda.",
    seeker_requests_card_rejected_desc: "Permintaan ditolak. Maklumat hubungan anda tidak dikongsi.",
    seeker_requests_card_approve_btn: "Luluskan",
    seeker_requests_card_reject_btn: "Tolak",
    employer_requests_login_title: "Permintaan Majikan",
    employer_requests_login_desc: "Masukkan nombor telefon anda untuk menjejaki status permintaan hubungan anda.",
    employer_requests_login_btn: "Jejaki Permintaan Saya",
    employer_requests_title: "Status Permintaan",
    employer_requests_subtitle: "Jejaki permintaan anda yang dihantar kepada pencari kerja.",
    employer_requests_stat_total: "Jumlah",
    employer_requests_stat_approved: "Diluluskan",
    employer_requests_stat_pending: "Menunggu",
    employer_requests_no_requests_title: "Tiada Permintaan Dihantar",
    employer_requests_no_requests_desc: "Anda belum menghantar sebarang permintaan hubungan dari nombor telefon ini.",
    employer_requests_card_requested_on: "Diminta pada",
    employer_requests_card_status_pending: "Menunggu",
    employer_requests_card_status_approved: "Diluluskan",
    employer_requests_card_status_rejected: "Ditolak",
    employer_requests_card_approved_title: "Maklumat Hubungan Diluluskan!",
    employer_requests_card_whatsapp_btn: "Sembang di WhatsApp",
    employer_requests_card_pending_desc: "Menunggu pencari kerja menyemak permintaan anda.",
    employer_requests_card_rejected_desc: "Permintaan anda telah ditolak oleh pencari kerja.",
    splash_welcome: "Selamat Datang ke",
  }
};

export type Language = 'en' | 'bn' | 'ms';
interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string, replacements?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Language>(() => (localStorage.getItem('xpatLang') as Language) || 'en');

  useEffect(() => {
    localStorage.setItem('xpatLang', lang);
    document.body.className = `bg-gradient-to-b from-dark-navy to-mid-navy ${lang === 'bn' ? 'font-bengali' : 'font-inter'}`;
  }, [lang]);

  const t = useCallback((key: string, replacements: Record<string, string> = {}): string => {
    let translation = (translations[lang] as any)[key] || (translations['en'] as any)[key] || key;
    Object.keys(replacements).forEach(rKey => {
        translation = translation.replace(`{${rKey}}`, replacements[rKey]);
    });
    return translation;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
